nota1 = float(input('Digite sua nota 1: '))
nota2 = float(input('Digite sua nota 2: '))
nota3 = float(input('Digite sua nota 3: '))
nota4 = float(input('Digite sua nota 4: '))
print(f'Sua média é \033[1:4:35:40m{(nota1 + nota2 + nota3 + nota4)/4}\033[m')