from time import sleep
print('=' * 25)
sleep(1)
print('Tocando música no Python3')
sleep(1)
print('=' * 25)
sleep(1)
print('Música == LiSA - Crossing Field (4:07)')
sleep(5)
print('')
print('Preparando...')
sleep(2)
from pygame import mixer
mixer.init()
mixer.music.load('saoOp.mp3')
sleep(2)
print('')
print('Carregada!')
sleep(2)
print('Começando a tocar...')
sleep(1)
mixer.music.play()
