# Generated by Django 5.1 on 2024-09-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Tarefas',
        ),
    ]
